_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/V3_0/scripts/optimize_hyperparameters.py
        e:
            0aywlnkmqk1vz1w7jwjcd7gcaxhgzytv:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "11811160064"
                args:
                    - --n-trials
                    - "1"
                    - --total-steps
                    - "1000"
                    - --eval-episodes
                    - "10"
                    - --out-dir
                    - /private/var/folders/fw/gt8mwzcx2vqcdqxdq3gnmqrc0000gn/T/pytest-of-kaan/pytest-8/test_hpo_basic_smoke0/hpo_run
                codePath: V3_0/scripts/optimize_hyperparameters.py
                codePathLocal: scripts/optimize_hyperparameters.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "238157180928"
                email: murat.seckin@std.bogazici.edu.tr
                executable: /Users/kaan/Desktop/Blackjack/.venv/bin/python
                git:
                    commit: 2632127fc988dc4fb757e2b8963d07a53ff78829
                    remote: https://github.com/kaannsckin/Blackjack.git
                host: kaan-MacBook-Air-9.local
                memory:
                    total: "8589934592"
                os: macOS-14.0-arm64-arm-64bit-Mach-O
                program: /Users/kaan/Desktop/Blackjack/V3_0/scripts/optimize_hyperparameters.py
                python: CPython 3.13.5
                root: /Users/kaan/Desktop/Blackjack/V3_0
                startedAt: "2025-07-10T20:45:32.417231Z"
                writerId: 0aywlnkmqk1vz1w7jwjcd7gcaxhgzytv
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 35
            "2":
                - 1
                - 35
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
eval_episodes:
    value: 10
n_trials:
    value: 1
out_dir:
    value: /private/var/folders/fw/gt8mwzcx2vqcdqxdq3gnmqrc0000gn/T/pytest-of-kaan/pytest-8/test_hpo_basic_smoke0/hpo_run
seed:
    value: 42
storage:
    value: null
study_name:
    value: bj_dqn_hpo
total_steps:
    value: 1000
